### ISSUE TITLE
Lexical Error memory exhausted 158.1-158.1

### ISSUE THREAD

**Issue by DavidJacksonPurdue** [BPHays/eastwood-public#1]
I received this error for homework 4. I have already compiled, ran the test cases, and have gotten 100, but running eastwood hw4.c gives me this error.

**Comment by BPHays** [comment]
This has to do with the nondeterministic parser that is being used. It's an issue with the number of consecutive whitespace characters and comments in a row. We need to change how we parse groups of those tokens and will push out a fix soon.

Anything like the following may cause issues:
``` C
int foo() {
  int x;
  // lots of empty lines
  ...

  int y;
...
```
Or
``` C
int x /* this is a comment */
        /* this is the next part */
        /* and more */
```

**Comment by BPHays** [comment]
An update has been pushed. It should work now.
