### ISSUE TITLE
Lexical Error syntax error 130.1-130.1

### ISSUE THREAD

**Issue by nbreen** [BPHays/eastwood-public#2]
I am getting this error when running against my code for hw4. My code compiles properly and consistently passes the test cases.

**Comment by BPHays** [comment]
In general you don't need to escape a newline. You can simply do:
``` C
int x = long_line +
  another_long_line
```
instead of
``` C
int x = long_line + \
  another_long_line
```

I'll update the linter to handle escaped newlines soon, but for now you should be able to just remove the backslash.

**Comment by BPHays** [comment]
The update has been pushed
