### ISSUE TITLE
Invalid Lexical Error: 98.1-98.1

### ISSUE THREAD

**Issue by nicholasgrose** [BPHays/eastwood-public#7]
Homework Number: 11

I am receiving lexical error 98.1-98.1 on hw11.c along with the message "If you are seeing this error make sure that your program compiles successfully, before submitting a bug report". Despite this, though, my code does compile (and gets a 100 on the test cases). I have double checked the line endings in the file, and can confirm that they are LF.

**Comment by BPHays** [comment]
This is an issue with the way that the linter handles types and is kind of a weakness of LR parsing in general.

The offending line is `tree_node * tree_node`. In general it is better to not shadow the type name with a variable name.
